#!/bin/sh

set -e

# Stop sickbeard service.
if pgrep -f SickBeard.py > /dev/null; then
    [ -e /etc/init.d/sickbeard ] && /etc/init.d/sickbeard stop
fi

# backup configfile if any
if [ -e /usr/share/sickbeard/autoProcessTV/autoProcessTV.cfg ]; then
    cp -f /usr/share/sickbeard/autoProcessTV/autoProcessTV.cfg /tmp/autoProcessTV.cfg
fi

# remove path if exists
if [ -d /usr/share/sickbeard ]; then
    rm -Rf /usr/share/sickbeard
fi

