#!/bin/sh

set -e

# stop sickbeard
if pgrep -f SickBeard.py > /dev/null; then
    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d sickbeard stop
    else
        /etc/init.d/sickbeard stop
    fi
fi

# make sure process is killed ok and pidfile is removed
if pgrep -f SickBeard.py > /dev/null; then
    rm -f $(ps up $(pgrep -f SickBeard.py) | grep pidfile | sed "s/.*--pidfile=//g") > /dev/null
    kill -9 $(pgrep -f SickBeard.py) > /dev/null
fi

# remove path if exists
if [ -d /usr/share/sickbeard ]; then
    rm -Rf /usr/share/sickbeard
fi

